global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7648017625:AAEu2_kgekUG2wMPx_Ez3icR4CsWUOwuA-4'
        chat_id: 1547317689
        message: |
          ğŸ”” Alert: {{ .CommonLabels.alertname }}
          ğŸ”¹ Severity: {{ .CommonLabels.severity }}
          ğŸ“ Instance: {{ .CommonLabels.instance }}
          ğŸ“ Description: {{ .CommonAnnotations.description }}
        parse_mode: "Markdown"
